---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.windows
  - name: chocolatey.chocolatey
  - name: community.aws
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.general
  - name: cloud.terraform

roles:
  - name: robertdebock.postfix
  - name: JonasPammer.gitlab
