---
- name: Prepopulate profiles on victim hosts
  hosts: windows_desktops:&victim
  gather_facts: no
  strategy: free
  vars:
    office_cfg_src_file: "{{ playbook_dir }}/../files/profiledir/registrymodifications.xcu"
    office_cfg_dest_dir: "AppData/Roaming/LibreOffice/4/muser"
    office_dest_prefix: "C:/Users"
    office_cfg_filename: "registrymodifications.xcu"
  vars_files:
    - ../vars/vars.yml
  tags:
    - office
    - libreoffice
    - profiledir
    - victim

  tasks:
    - name: prepop profile dirs for victim desktops
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../library/prepop-profile-directories.yml"
      vars:
        prepop_domain_users: "{{ domain_users }}"
        office_cfg_src_file: "../files/profiledir/registrymodifications.xcu"
        office_cfg_dest_dir: "AppData/Roaming/LibreOffice/4/user"
        office_dest_prefix: "C:/Users"
        office_cfg_filename: "registrymodifications.xcu"
